import numpy as np
import matplotlib.pyplot as plt
plt.set_cmap('Greys')
nx = 256
ny = 256
imin = np.fromfile("grain_vis.dat")
#imin = np.fromfile("30571_seg.dat", offset=0)
#imin = np.fromfile("ACnon_100.dat", offset=4)
#imin = np.fromfile("ACcon_non400.dat", offset=4)
#imin = np.fromfile("piecestest/ACcon_big.dat", offset=4)
#imin = np.fromfile("piecestest/in0002.dat", offset=4)
print(len(imin))
im = imin.reshape([nx,ny],order='F')
#im = imin.reshape([150,173,90],order='F')
#im = imin.reshape([150,345,360],order='F')

print(im.shape)
print(im[0,0],im[-1,-1])
print(np.amax(imin),np.amin(imin))

stem='CHds2_t0010k'
#stem = 'AC100'
# plot faces
fig = plt.figure(figsize=(3,3))
fig.patch.set_visible(False)
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[0,:], origin='lower')
fig.savefig(stem+'x0.pdf',dpi=300)
fig.clear()
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[:,0], origin='lower')
fig.savefig(stem+'y0.pdf',dpi=300)
fig.clear()
#ax = fig.add_axes((0,0,1,1))
#ax.set_axis_off()
#axim = ax.imshow(im[:,:,0], origin='lower')
#fig.savefig(stem+'z0.pdf',dpi=300)
#fig.clear()

ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[-1,:], origin='lower')
fig.savefig(stem+'x1.pdf',dpi=300)
fig.clear()
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[:,-1], origin='lower')
fig.savefig(stem+'y1.pdf',dpi=300)
fig.clear()
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[:,:], origin='lower')
fig.savefig(stem+'y1.pdf',dpi=300)
fig.clear()
#ax = fig.add_axes((0,0,1,1))
#ax.set_axis_off()
#axim = ax.imshow(im[:,:,-1], origin='lower')
#fig.savefig(stem+'z1.pdf',dpi=300)
#fig.clear()

"""
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[int(nx/2),:], origin='lower')
fig.savefig(stem+'x12.pdf',dpi=300)
fig.clear()
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[int(nx/2)+1,:], origin='lower')
fig.savefig(stem+'x12_1.pdf',dpi=300)
fig.clear()
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[int(nx/2)+2,:], origin='lower')
fig.savefig(stem+'x12_2.pdf',dpi=300)
fig.clear()
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[int(nx/3),:], origin='lower')
fig.savefig(stem+'x13.pdf',dpi=300)
fig.clear()
ax = fig.add_axes((0,0,1,1))
ax.set_axis_off()
axim = ax.imshow(im[int(2*nx/3),:], origin='lower')
fig.savefig(stem+'x23.pdf',dpi=300)
fig.clear()
"""
